project 'todo.xcodeproj'

# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'todo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for todo
 pod 'Alamofire', '~> 4.5'
 pod 'SnapKit', '~> 4.0.0'
 pod 'Moya','~>10.0.1'

end
